language: node_js
sudo: false
node_js:
  - '0.10'
before_install:
  - npm install -g grunt-cli
install: npm install
script:
  - grunt
deploy:
  provider: releases
  api_key:
    secure: AXggnsDClUChq5mRqudXKiDS8g5Mbjv0J/vEOj5vdVYxJgII2+pHcJpFAEtU0hKjiMgWPTtLDDUmjS61iGI9WcxrNKKwGohhORXQk/CPxRUA69AaXOPOUP1p0Sdcyy2NM1NJ1N75mhDkYfrnhlVuafSPKb8DaSjsyjD0JdIoXe4=
  file:
    - $TRAVIS_BUILD_DIR/dist/feedhenry-js.zip
    - $TRAVIS_BUILD_DIR/dist/feedhenry-titanium.zip
    - $TRAVIS_BUILD_DIR/dist/fh-starter-project-latest.zip
  skip_cleanup: true
  on:
    repo: feedhenry/fh-js-sdk
    tags: true
    all_branches: true